syntax enable

set autoindent
set background=dark
set expandtab " replace tab character with spaces
set ignorecase
set number
set relativenumber
set ruler
set shiftwidth=2
set softtabstop=2
set tabstop=2
set hlsearch
set ignorecase
colorscheme default

" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin('~/.vim/bundle')
Plug 'junegunn/vim-plug' " Get help for vim-plug itself
Plug 'pearofducks/ansible-vim'
