syntax enable

set autoindent
set spell spelllang=en_gb
set background=dark
set expandtab " replace tab character with spaces
set ignorecase
set number
set relativenumber
set ruler
set shiftwidth=2
set softtabstop=2
set tabstop=2
set hlsearch
set ignorecase
set laststatus=2
colorscheme default

" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin('~/.vim/bundle')
  Plug 'junegunn/vim-plug' " Get help for vim-plug itself
  Plug 'pearofducks/ansible-vim'
  Plug 'yuttie/comfortable-motion.vim'
  Plug 'ctrlpvim/ctrlp.vim'


call plug#end()

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra' " use current git repo/file director with ctrl p 

map <C-n> :NERDTreeToggle<CR> " Toggle nerdtree 
