syntax enable

set autoindent
set background=dark
set clipboard=unnamed
set complete+=kspell          " Autocomplete dictionary words when spell check is on
set encoding=utf-8
set expandtab                 " replace tab character with spaces
set hlsearch
set ignorecase
set ignorecase
set incsearch
set laststatus=2
set list listchars=tab:»\ ,trail:·
set number
set path=.,**
set relativenumber
set ruler
set shiftwidth=2
set showcmd
set smarttab
set softtabstop=2
set spellfile=~/.dotfiles/vim/spell/en.utf-8.add
set spelllang=en_gb
set spellsuggest=fast,20
set tabstop=2
set visualbell t_vb=          " Turn off bell

" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin('~/.vim/bundle')

  Plug 'ctrlpvim/ctrlp.vim'
  Plug 'godlygeek/tabular' | Plug 'tpope/vim-markdown'
  Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
  Plug 'junegunn/vim-plug' " Get help for vim-plug itself
  Plug 'jvirtanen/vim-hcl' " Syntax for hashi corp language frameworks
  Plug 'machakann/vim-highlightedyank' " Briefly highlight the text yanked
  Plug 'pearofducks/ansible-vim'
  Plug 'preservim/nerdtree'
  Plug 'stephpy/vim-yaml'
  Plug 'tarekbecker/vim-yaml-formatter'
  Plug 'tpope/vim-commentary'
  Plug 'tpope/vim-fugitive'
  Plug 'tpope/vim-repeat'
  Plug 'tpope/vim-surround'
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  Plug 'vim-python/python-syntax'
  Plug 'vim-scripts/AutoComplPop'
  Plug 'vim-scripts/ReplaceWithRegister'
  Plug 'yuttie/comfortable-motion.vim'
  Plug 'morhetz/gruvbox'

call plug#end()

colorscheme gruvbox

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra' " use current git repo/file director with ctrl p 

map <C-n> :NERDTreeToggle<CR> " Toggle nerdtree 
" let g:lightline = {
"       \ 'colorscheme': 'wombat',
"       \ 'active': {
"       \   'left': [ [ 'mode', 'paste' ],
"       \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
"       \ },
"       \ 'component_function': {
"       \   'gitbranch': 'FugitiveHead'
"       \ },
"       \ }

" ******************** Start: Key remapping ***********************

" Leader mapping
let mapleader = " "

nnoremap ]r :ALENextWrap<CR> " Nex linting error
nnoremap [r :ALEPreviousWrap<CR>
nnoremap <leader>o :Files <CR>
noremap <F5> :setlocal spell!<CR> " Toggle spell check.
noremap <F6> :set invrelativenumber<CR> " Toggle relative line numbers and regular line numbers.
inoremap jk <Esc>
vnoremap jk <Esc>
nnoremap <leader>- :vsplit<CR>
nnoremap <leader>\ :split<CR>

" ******************** End: Key remapping ***********************

if !empty(glob('~/.vimrc.local'))
  source ~/.vimrc.local
endif

" ******************* Start: Tabline *************************
let g:airline_theme='solarized'
let g:airline_solarized_bg='dark'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'default'
" ******************* End: Tabline ****************************

"  ****************** Start: File types ************************
autocmd FileType java set tabstop=8 softtabstop=4 shiftwidth=4
autocmd FileType groovy set tabstop=8 softtabstop=4 shiftwidth=4
autocmd CursorHoldI,CursorHold * update " automatically save when cursor stops moving

"  ****************** End: filetypes ************************
