- name: Create directories and copy files
  hosts: localhost
  tasks:
  - name: Create directory
    file:
      path: ~/.config/vim
      state: directory
      recurse: yes
  - copy:
      src: "../config/gitconfig"
      dest: "~/.config/gitconfig"

- name: Ensure homebrew packages are installed.
  hosts: localhost
  tasks:
  - homebrew:
      name: bat
      state: latest
  - homebrew:
      name: jq
      state: latest
  - homebrew:
      name: tree
      state: latest
  - homebrew:
      name: tmux
      state: latest
- name: Create symbolic link 
  hosts: localhost
  tasks:
  - file:
      src: "~/.config/gitconfig"
      dest: "~/.gitconfig"
      state: link
