- name: Install packages
  hosts: localhost
  tasks:
    - name: Install packages
      homebrew:
        name: 
          - bat
          - jq
          - tree
          - tmux
        state: latest

- name: Copy files
  hosts: localhost
  tasks:
  - name: Copy files
    copy:
      src: "../{{ item }}"
      dest: "~/.dotfiles/"
    with_items:
      - git
      - vim 
      - shell

- name: Create symbolic link 
  hosts: localhost
  tasks:
  - name: Create symbolic link 
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    with_items:
      - { dest: "~/.gitconfig", src: "~/.dotfiles/git/gitconfig" }
      - { dest: "~/.vimrc", src: "~/.dotfiles/vim/vimrc" }
