- name: Create directories and copy files
  hosts: localhost
  tasks:
  - name: Create directory
    file:
      path: ~/.config/vim
      state: directory
      recurse: yes
  - copy:
      src: "../git"
      dest: "~/.dotfiles/"

- name: Ensure homebrew packages are installed.
  hosts: localhost
  tasks:
    - name: Install packages
      homebrew:
        name: 
          - bat
          - jq
          - tree
          - tmux
        state: latest
- name: Create symbolic link 
  hosts: localhost
  tasks:
  - file:
      src: "~/.dotfiles/git/gitconfig"
      dest: "~/.gitconfig"
      state: link
